swiftlang/swift-package-collection-generator

- Tests/PackageCollectionGeneratorExecutableTests/PackageCollectionGenerateTests.swift
Hi @yim-lee , I've had a first look into incorporating the collection generator into the SPI and while doing so I found it helpful to change the end-to-end test from a shell-out command into a parsed command that calls `run()`. That way it was easier to step through it with the debugger - or am I missing a way that could be done with the shell-out command?
I can see how that isn't quite a true end-to-end test anymore though, so maybe that's not something you'd like to change.
Just a thought!
> Make it a little easier to study the command

- Package.swift
- Sources/PackageCollectionDiff/PackageCollectionDiff.swift
- Sources/PackageCollectionDiff/README.md
- Sources/PackageCollectionDiffExecutable/main.swift
- Sources/PackageCollectionValidator/README.md
- Tests/PackageCollectionDiffExecutableTests/Inputs/test.json
- Tests/PackageCollectionDiffExecutableTests/Inputs/test_diff_generated_at.json
- Tests/PackageCollectionDiffExecutableTests/Inputs/test_diff_packages.json
- Tests/PackageCollectionDiffExecutableTests/PackageCollectionDiffTests.swift
This is useful in automation to compare if the newly generated collection is different from the one previously generated, for example.
> Add package-collection-diff command

- Sources/PackageCollectionGenerator/Models/PackageCollectionExtensions.swift
- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
- Sources/Utilities/Git.swift
- Tests/PackageCollectionGeneratorExecutableTests/PackageCollectionGenerateTests.swift
Requires https://github.com/apple/swift-package-manager/pull/3266
The `generate` tool will try to obtain message and timestamp for **annotated** tags only. In most use-cases, tag is created as part of a (GitHub) release and is "lightweight", which is the opposite of annotated and the information we get with `git` would not be suitable.
> Add summary and createdAt to package version

- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
New `ProductType.extension` recently introduced in SwiftPM
> Fix compilation error

- Sources/PackageCollectionGenerator/README.md
Update the generator readme to reflect the correct parameter names. It looks like #5 changed these to `description`, but then #6 changed them back. (I think I preferred both using `description`...)
> Update PackageCollectionGenerator/README.md to use correct 'overview' & 'summary' parameters

- docker/docker-compose.yaml
> Remove -warnings-as-errors flag from docker builds

- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
Fix a build failure caused by SwiftPM upstream renaming `ProductType.extension` to `ProductType.plugin` in https://github.com/apple/swift-package-manager/pull/3311.
Note that [SwiftPM's `PackageCollectionModel.V1.ProductType`](https://github.com/apple/swift-package-manager/blob/d1ef83796730d76754db58d327e7fd02bc785e97/Sources/PackageCollectionsModel/PackageCollectionModel%2Bv1.swift#L336-L374) hasn't gotten this rename yet and still has `ProductType.extension`, which seems like a mismatch that probably needs to be resolved upstream (and then again here).
/cc @abertelrud @yim-lee
> Update PackageCollectionModel.V1.ProductType init extension for `.extension` → `.plugin` renaming

- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
- Tests/PackageCollectionGeneratorExecutableTests/PackageCollectionGenerateTests.swift
Motivation:
The subdirectory name used for cloning a repo under the cache directory is extracted from the repo's URL. Currently it only works if the URL contains `.git` suffix.
Modification:
Improve the regex (copied from SwiftPM) so that `.git` suffix is optional.
> Improve regex for extracting repository name from git URL

- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
motivation: some packages use a "v1.2.3" tagging schema which is supported by SwiftPM but not by the geenrator
changes: drop "v" prefix prior to parsing the tag as verion
> fix version parsing when the tag includes a "v" prefix

- Sources/PackageCollectionGenerator/Models/PackageCollectionGeneratorInput.swift
- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
- Sources/PackageCollectionGenerator/README.md
- Tests/PackageCollectionGeneratorExecutableTests/PackageCollectionGenerateTests.swift
- Tests/PackageCollectionGeneratorTests/Inputs/test-input.json
- Tests/PackageCollectionGeneratorTests/PackageCollectionGeneratorInputTests.swift
Motivation:
Currently a package's versions are determined by:
1. The latest versions in the git repository. This list changes automatically each time the generator runs.
2. A specific list of versions defined using `versions` in the generator input file. This requires manual update.
It would be nice if the generator supports a third option: "use the latetst versions except [versions]"
Modifications:
Add `excludedVersions` to generator input so that certain versions can be excluded of a collection regardless of how the generator computes the list  of package versions.
> Add 'excludedVersions' to generator input

- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
- Sources/PackageCollectionGenerator/PackageMetadataProviders/GitHubPackageMetadataProvider.swift
- Print error in case the generator fails to fetch additional metadata
- Increase GitHub API request timeout from 1s to 2s
> Improve diagnostics

- Sources/PackageCollectionDiff/PackageCollectionDiff.swift
- Sources/PackageCollectionDiff/README.md
- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
- Sources/PackageCollectionGenerator/README.md
- Sources/PackageCollectionSigner/PackageCollectionSign.swift
- Sources/PackageCollectionSigner/README.md
- Sources/PackageCollectionValidator/PackageCollectionValidate.swift
- Sources/PackageCollectionValidator/README.md
Allow short `-v` verbose flag in all commands, in addition to `--verbose`. The `-v` flag is well understood and allowing it in these commands matches what we already have for `-h`/`--help`.
> Allow short -v verbose flag in all commands

- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
- Sources/PackageCollectionGenerator/README.md
- Tests/PackageCollectionGeneratorExecutableTests/PackageCollectionGenerateTests.swift
Adds a `--pretty-printed` flag to package-collection-generate that nicely formats the collection output.
Fixes rdar://73019498.
> Add --pretty-printed command to package-collection-generate

- scripts/soundness.sh
Previously the script would exit ~silently if swiftformat was not installed.
> Add hint to scripts/soundness.sh about swiftformat installation

- Tests/PackageCollectionGeneratorExecutableTests/PackageCollectionGenerateTests.swift
- docker/docker-compose.1804.54.yaml
- docker/docker-compose.2004.55.yaml
- `XCTAttachment` is available through Xcode only, so skip the
pretty-print flag test when running on Linux.
- Update docker builds. Add 5.5.
> Fix test in Linux and update docker builds

- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
Motivation:
A new product type `snippet` was recently added, causing compilation
errors.
Modifications:
Handle new `snippet` type.
> Add support for new 'snippet' product type

- Package.swift
- Tests/PackageCollectionSignerExecutableTests/PackageCollectionSignTests.swift
Matching upstream changes suggested in https://github.com/apple/swift-package-manager/pull/3831
> Adopt new PackageCollectionSigner interface

- README.md
After encountering the issue that's [described here](https://forums.swift.org/t/package-collection-generator-not-found/49631), I figured it would be really useful to document the process of installing and using the Package Collection Generator locally from the command line.
AFAIK, this is the standard process for building and installing local SPM executables, but I can certainly modify the instructions if anything looks incorrect.
> Add local installation instructions to README

- Sources/Utilities/Git.swift
GitHub repository names can contain the `.` character, such as `https://github.com/groue/GRDB.swift`. If your collection has a repo like that, `package-collection-generate` ignores it with
```
Failed to fetch additional metadata: invalidGitURL(https://github.com/groue/GRDB.swift)
```
This patch fixes this by changing the regex to explicitly allow the characters `[a-z0-9._-]` in the repo name, and dropping the `.git` suffix if it is present.
> Update GitURL.from(_:) to accept repo names with .

- Sources/PackageCollectionGenerator/Models/PackageCollectionGeneratorInput.swift
- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
- Tests/PackageCollectionGeneratorTests/Inputs/test-input.json
- Tests/PackageCollectionGeneratorTests/PackageCollectionGenerateTests.swift
- Tests/PackageCollectionGeneratorTests/PackageCollectionGeneratorInputTests.swift
Motivation:
A package version in a package collection can have `signer`, which was added https://github.com/apple/swift-package-manager/pull/6415
Modification:
Add `signer` to package level input. If set, all versions of the package will have that `signer`.
> Add package 'signer' to input

- Package.swift
- Sources/PackageCollectionDiff/PackageCollectionDiff.swift
- Sources/PackageCollectionGenerator/Models/PackageCollectionGeneratorInput.swift
- Sources/PackageCollectionGenerator/PackageCollectionGenerate.swift
- Sources/PackageCollectionSigner/PackageCollectionSign.swift
- Sources/PackageCollectionValidator/PackageCollectionValidate.swift
- Sources/Utilities/Git.swift
- Sources/Utilities/Path.swift
- Tests/PackageCollectionDiffTests/PackageCollectionDiffTests.swift
- Tests/PackageCollectionGeneratorTests/GitHubPackageMetadataProviderTests.swift
- Tests/PackageCollectionGeneratorTests/PackageCollectionGenerateTests.swift
- Tests/PackageCollectionGeneratorTests/PackageCollectionGeneratorInputTests.swift
- Tests/PackageCollectionSignerTests/PackageCollectionSignTests.swift
- Tests/PackageCollectionValidatorTests/PackageCollectionValidateTests.swift
SwiftPM has its versions of `AbsolutePath` and `withTemporaryDirectory`, causing ambiguous call errors.
> Adjust code to use Basics API rather than TSC

- Package.swift
- Sources/PackageCollectionSigner/PackageCollectionSign.swift
- Tests/PackageCollectionSignerTests/PackageCollectionSignTests.swift
https://github.com/apple/swift-package-manager/pull/6609
> Adjust to PackageCollectionSigning changes
